### ISSUE TITLE
xBark Title

### ISSUE THREAD

**Issue by Barkpuppy1** [BCNFreedom/BarkCraftMod#1]
i want a xBark Title i can add to myself and other players but it will added in a file named xBark.yml

**Comment by fluffycq** [comment]
Wouldn't be possible, and its useless.

**Comment by AvalancheYT** [comment]
@fluffycq, it's possible and if the owner wants to add feature, I reckon you should add it.

**Comment by jakeHq** [comment]
no thanks.
