### ISSUE TITLE
TotalFreedomMod Licensing

### ISSUE THREAD

**Issue by AvalancheYT** [BCNFreedom/BarkCraftMod#3]
Hello,

It has come to my attention that this repository contains copyrighted material in violation of its provided license.
The material in question is released under the TotalFreedom General License (TFGL) Version 1.0 or Version 2.0 depending on the time infringing material was introduced to this repository.

Copyrighted material included in this repository violates its license due to one or more of the following:

Redistributions of the material do not retain its copyright license in its exact form.
The original authors of this software have been misrepresented or not reprepresented at all in one or more of the following locations:
* _plugin.yml_ under ```authors```
* _README.md_
* _FUtil.java_ under ```DEVELOPERS```
* Redistributions of the material in question are available in non-source, object, packaged or compiled form.

In order to comply with the infringed material's license and its copyright restrictions, please either:
a) Remove the copyrighted material from this repository; or
b) Edit or adjust the required source files as necessary to comply with TFGL.

I hope to have properly and sufficiently informed you of the violations in this repository. If you have any further questions, don't hesitate to contact me.

Thanks in advance,
Jerom

Read what it says and make the changes. I know I am not in charge of TFM projects but this has caught my attention.

If you got any issues, please contact @JeromSar, not me.

**Comment by jakeHq** [comment]
What do you mean?

**Comment by jakeHq** [comment]
n0ice lie m8 
authors: [Madgeek1450, Prozza]

**Comment by jakeHq** [comment]
aaaand.     public static final List<String> DEVELOPERS = Arrays.asList("Madgeek1450", "Prozza", "Wild1145", "WickedGamingUK");

**Comment by AvalancheYT** [comment]
You have deleted/misuploaded the License.

**Comment by JeromSar** [comment]
@AvalancheYT Please do _not_ post on my behalf.

**Comment by Barkpuppy1** [comment]
@AvalancheYT you should have tagged Fluffycq because i do not really even do any thing for this
